"""Aether-2 tool surface."""

from harness.aether2.tools.mcp import (
    ConfigScope,
    FakeLocalMcpServer,
    LocalMcpServer,
    McpConnectionState,
    McpDiscoveredTool,
    McpSchemaMappingIssue,
    McpServerConfig,
    McpServerConnection,
    McpServerUnavailableError,
    McpToolDescriptor,
    McpToolExecutionError,
    McpToolResult,
    McpToolTimeoutError,
    McpTransport,
    build_mcp_tool_name,
    connect_fake_local_server,
    disabled_mcp_server,
    discover_mcp_tools,
    failed_mcp_server,
    invoke_mcp_tool,
    map_mcp_tool_to_schema,
    normalize_name_for_mcp,
)
from harness.aether2.tools.native import TOOL_NAMES, TOOL_SCHEMAS, ToolDispatchOutcome, dispatch, dispatch_with_hooks
from harness.aether2.tools.permissions import PermissionAudit, PermissionManager, PermissionPolicy, PermissionRule
from harness.aether2.tools.registry import RegisteredTool, ToolKind, ToolRegistry, ToolRegistryIssue, build_native_tool_registry

__all__ = [
    "ConfigScope",
    "FakeLocalMcpServer",
    "LocalMcpServer",
    "McpConnectionState",
    "McpDiscoveredTool",
    "McpSchemaMappingIssue",
    "McpServerConfig",
    "McpServerConnection",
    "McpServerUnavailableError",
    "McpToolDescriptor",
    "McpToolExecutionError",
    "McpToolResult",
    "McpToolTimeoutError",
    "McpTransport",
    "PermissionAudit",
    "PermissionManager",
    "PermissionPolicy",
    "PermissionRule",
    "RegisteredTool",
    "TOOL_NAMES",
    "TOOL_SCHEMAS",
    "ToolDispatchOutcome",
    "ToolKind",
    "ToolRegistry",
    "ToolRegistryIssue",
    "build_mcp_tool_name",
    "build_native_tool_registry",
    "connect_fake_local_server",
    "disabled_mcp_server",
    "dispatch",
    "dispatch_with_hooks",
    "discover_mcp_tools",
    "failed_mcp_server",
    "invoke_mcp_tool",
    "map_mcp_tool_to_schema",
    "normalize_name_for_mcp",
]
