"""Aether-2 skills loader, registry, and visible invocation helpers."""

from harness.aether2.skills.invocation import RenderedSkillContext, build_skill_prefix_message, render_skill_context_block
from harness.aether2.skills.loader import (
    LoadedFrom,
    ParsedSkillFrontmatter,
    SkillExecutionContext,
    SkillHookCommand,
    SkillHookEvent,
    SkillHookMatcher,
    SkillHookMetadata,
    SkillLoadIssue,
    SkillLoadResult,
    SkillSource,
    SkillSpec,
    create_skill_spec,
    discover_skill_directories_for_paths,
    estimate_skill_frontmatter_tokens,
    load_skills_from_directory,
    parse_frontmatter_document,
    parse_skill_frontmatter_fields,
    skill_matches_paths,
)
from harness.aether2.skills.registry import (
    BundledSkillDefinition,
    LinkedMcpTool,
    MCPSkillBuilders,
    SkillRegistry,
    SkillRegistryIssue,
    SkillSelectionResult,
    clear_bundled_skills,
    extract_bundled_skill_files,
    get_bundled_skill_definitions,
    get_mcp_skill_builders,
    materialize_bundled_skill,
    register_bundled_skill,
    register_mcp_skill_builders,
)

__all__ = [
    "BundledSkillDefinition",
    "LinkedMcpTool",
    "LoadedFrom",
    "MCPSkillBuilders",
    "ParsedSkillFrontmatter",
    "RenderedSkillContext",
    "SkillExecutionContext",
    "SkillHookCommand",
    "SkillHookEvent",
    "SkillHookMatcher",
    "SkillHookMetadata",
    "SkillLoadIssue",
    "SkillLoadResult",
    "SkillRegistry",
    "SkillRegistryIssue",
    "SkillSelectionResult",
    "SkillSource",
    "SkillSpec",
    "build_skill_prefix_message",
    "clear_bundled_skills",
    "create_skill_spec",
    "discover_skill_directories_for_paths",
    "estimate_skill_frontmatter_tokens",
    "extract_bundled_skill_files",
    "get_bundled_skill_definitions",
    "get_mcp_skill_builders",
    "load_skills_from_directory",
    "materialize_bundled_skill",
    "parse_frontmatter_document",
    "parse_skill_frontmatter_fields",
    "register_bundled_skill",
    "register_mcp_skill_builders",
    "render_skill_context_block",
    "skill_matches_paths",
]
