"""Trace and receipt primitives for the public harness namespace."""

from harness.aether2.traces.delta import (
    DeltaReport,
    FileDelta,
    StateSnapshot,
    build_evidence_ledger,
    diff,
    ensure_stated_requirements,
    mark_blockers_candidate_resolved,
    mark_blockers_exhausted,
    record_check_results,
    record_observation_evidence,
    record_terminal_claim,
    record_verifier_report,
    serialize_evidence_ledger,
    snapshot,
    with_evidence_ledger,
)
from harness.aether2.traces.decision_trace import (
    NON_COT_NOTE,
    build_and_write_bundle,
    build_parser,
    collect_decision_trace_bundle,
    main,
    render_summary,
    summarize_text,
)
from harness.aether2.traces.envelope import (
    ErrorInfo,
    ObservationEnvelope,
    ProcessDelta,
    TruncationDigest,
    TruncationDigestEntry,
    build_envelope,
    collapse_cr_ansi,
)
from harness.aether2.traces.mirror import Mirror, MirrorNote, SemanticObservation
from harness.aether2.traces.receipts import ReceiptWriter

__all__ = [
    "DeltaReport",
    "ErrorInfo",
    "FileDelta",
    "Mirror",
    "MirrorNote",
    "NON_COT_NOTE",
    "ObservationEnvelope",
    "ProcessDelta",
    "ReceiptWriter",
    "SemanticObservation",
    "StateSnapshot",
    "TruncationDigest",
    "TruncationDigestEntry",
    "build_and_write_bundle",
    "build_envelope",
    "build_evidence_ledger",
    "build_parser",
    "collect_decision_trace_bundle",
    "collapse_cr_ansi",
    "diff",
    "ensure_stated_requirements",
    "main",
    "mark_blockers_candidate_resolved",
    "mark_blockers_exhausted",
    "record_check_results",
    "record_observation_evidence",
    "record_terminal_claim",
    "record_verifier_report",
    "render_summary",
    "serialize_evidence_ledger",
    "snapshot",
    "summarize_text",
    "with_evidence_ledger",
]
